project:
  type: website

website:
  title: Final Project Elizabeth Ladd INFO 526 
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-SU26/final-project-ekladd # Needs to be changed to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
